/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Aula03;

public class App {
    public static void main(String[] args) {
        
        País novoPaís = new País ("America do Sul", "Brasil");
        
        novoPaís.exibirPaís();
        
        System.out.println("");
        
        Estado novoEstado = new Estado ("America do Sul", "Brasil", "Rio Grande do Sul", "Porto Alegre");
        
        novoEstado.exibirPaís();
        
        System.out.println("");
        
        Capital novaCapital = new Capital ("America do Sul", "Brasil", "Brasilia");
        
        novaCapital.exibirPaís();
        
    }
}
