/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Interfaces;

public class Banda {
    public static void main(String[] args) {
        
        Violao violao = new Violao();
        
        ContraBaixo contraBaixo = new ContraBaixo();
        
        Violino violino = new Violino();
        
        violao.afinar();
        contraBaixo.afinar();
        violino.afinar();
        
        violao.tocar();
        contraBaixo.tocar();
        violino.tocar();
        
    }
}
