/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RPG;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);
        Personagem pokemon = new Bulbasaur();
        
        System.out.println ("Ola! Bem-vindo ao mundo dos POKEMON! Meu nome e Carvalho! "
            + "As pessoas me chamam de PROF. POKEMON! Este mundo e habitado por criaturas chamadas POKEMON! "
            + "Para algumas pessoas, POKEMON sao animais de estimacao. "
            + "Outros os usam para lutas. Eu... eu estudo POKEMON como profissao. \nPrimeiro, qual e o seu nome?\n");
    
        String treinador = scanner.nextLine();
        
        System.out.println("Certo! Entao seu nome e " + treinador + "! Prazer em conhece-lo! Voce acabou de completar 10 anos e tem direito a escolher "
                + "seu POKEMON inicial! Ele ira te acompanhar em sua aventura pelo mundo POKEMON, sendo seu companheiro e leal amigo, tambem te ajudando em possiveis batalhas no caminho. "
                + "\nAqui no laboratorio temos 3 escolhas, permita-me apresenta-las: "
                + "\n"
                + "\n1. Bulbasaur - O POKEMON bulbo do tipo Planta e Veneno"
                + "\n"
                + "\nAtaque: 10"
                + "\nVida: 14"
                + "\nMana: 18"
                + "\n"
                + "\n2. Squirtle - O POKEMON tartaruga do tipo Agua"
                + "\n"
                + "\nAtaque: 14"
                + "\nVida: 18"
                + "\nMana: 10"
                + "\n"
                + "\n3. Charmander - O POKEMON salamandra do tipo Fogo"
                + "\n"
                + "\nAtaque: 18"
                + "\nVida: 10"
                + "\nMana: 14"
                + "\n"
                + "\nEntao, qual sua escolha?\n");
        
        int escolhaPokemon = scanner.nextInt();
        
         if (escolhaPokemon == 1) {
            
            pokemon = new Bulbasaur();
                    
         } else if (escolhaPokemon == 2) {
        
            pokemon = new Squirtle();
                
         } else if (escolhaPokemon == 3) {
        
            pokemon = new Charmander();
                
         } else {
                
            System.out.println("Escolha invalida, erro!");
            System.exit(0);
            
         }
         
         System.out.println("Certo! Seu primeiro parceiro em sua jornada e " + pokemon.nome);
         
         
    }
}

