/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ArrayList;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    private final Scanner scanner = new Scanner(System.in);
    private final ArrayList<String> itens = new ArrayList<>();
    private final ArrayList<Integer> precos = new ArrayList<>();

    private void removerItem() {
        if (itens.isEmpty()) {
            System.out.println("Seu carrinho está vazio!");
            return;
        }

        System.out.println("\n--- Remover Item ---");
        for (int i = 0; i < itens.size(); i++) {
            System.out.println(i + ". " + itens.get(i) + " - R$" + precos.get(i));
        }

        System.out.print("\nEscolha um item para remover (ou -1 para voltar): ");
        int indice = scanner.nextInt();
        if (indice >= 0 && indice < itens.size()) {
            System.out.println(itens.get(indice) + " removido do carrinho!");
            itens.remove(indice);
            precos.remove(indice);
        } else {
            System.out.println("Opção inválida.");
        }
    }

    private void verCarrinho() {
        if (itens.isEmpty()) {
            System.out.println("Seu carrinho está vazio!");
            return;
        }

        System.out.println("\n--- Carrinho de Compras ---");
        int total = 0;
        for (int i = 0; i < itens.size(); i++) {
            System.out.println(itens.get(i) + " - R$" + precos.get(i));
            total += precos.get(i);
        }
        System.out.println("Total: R$" + total);
    }

    private void pagar() {
        if (itens.isEmpty()) {
            System.out.println("Seu carrinho está vazio!");
            return;
        }

        int total = 0;
        for (int preco : precos) {
            total += preco;
        }

        System.out.println("\n--- Pagamento ---");
        System.out.println("Total da compra: R$" + total);
        System.out.println("Pagamento realizado com sucesso! Obrigado por comprar no Mercado do Povo.");
        
        System.exit(0);
    }

    public void menu(){
        System.out.println("MERCADO DO POVO!!!");
        System.out.println("");
        System.out.println("1. Alimentos Industrializados");
        System.out.println("2. Alimentos Organicos");
        System.out.println("3. Ferramentas");
        System.out.println("4. Eletrodomesticos");
        System.out.println("5. ???");
        System.out.println("6. Remover Item");
        System.out.println("7. Ver Carrinho");
        System.out.println("8. Pagar");
        System.out.println("9. Sair");
    }

    public boolean escolha(int opcao) {
        Industrializados industrializados = new Industrializados();

        switch (opcao) {
            case 1:

                System.out.println("\nEscolha um produto pelo indice: ");

                String[] nomes = industrializados.nome();
                int[] precosLista = industrializados.preco();

                for (int i = 0; i < nomes.length; i++) {
                    System.out.println(i + ". " + nomes[i] + " - R$" + precosLista[i]);
                }


                int alternativa = scanner.nextInt();
                if (alternativa >= 0 && alternativa < nomes.length) {
                    itens.add(nomes[alternativa]);
                    precos.add(precosLista[alternativa]);
                    System.out.println(nomes[alternativa] + " adicionado ao carrinho!");
                } else {
                    System.out.println("Opcao invalida.");
                }

                break;

            case 2:

                System.out.println("");

                break;

            case 3:

                System.out.println("");

                break;

            case 4:

                System.out.println("");

                break;

            case 5:

                System.out.println("");

                break;

            case 6:

                removerItem();

                break;

            case 7:

                verCarrinho();

                break;

            case 8:

                pagar();

                break;

            case 9:

                System.out.println("Bye bye!");

                return true;

            default:
                System.out.println("Opcao invalida!");

        }

        return false;
    }

    public void main() {
        boolean encerrar = false;
        App app = new App();
        Scanner scanner = new Scanner(System.in);

        while (!encerrar) {
            app.menu();
            System.out.println("\nEscolha uma opcao: ");
            int opcao = scanner.nextInt();
            encerrar = app.escolha(opcao);
        }
    }

    public static void main(String[] args) {
        App app = new App();

        app.main();
    }
}
