/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Aula01;

public class App {


    public static void main(String[] args) {
        
        String meuNome = "Felipe";
        
        char minhaInicial = 'F';
        
        int minhaIdade = 19;
        
        double minhaAltura = 1.90;
        
        boolean souAluno = true;
        
        System.out.println("Boa noite!" + " Meu nome eh " + meuNome + " e tenho " + minhaIdade + " anos." );
    }
}


