/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Interfaces;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       Bandap classUnderTest = newBandap();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
